server:
  port: 8081
spring:
  application:
    name: microservice-customer
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    integration:
      enabled: true
